language: node_js
node_js:
  - 5.4.1
notifications:
  walter.wgbn@gmail.com
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - bower install
  - webdrive-manager update
before_script:
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS